---

- hosts: docker_swarm_manager
  tasks:
    - name: Elasticsearch | Create container
      docker_container:
        name: "es_{{ inventory_hostname }}"
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        volumes:
          - /var/sonyc:/var/sonyc
        ports:
          - 9200:9200
          - 9300:9300    
        env:
          node.name: "es01"
          node.master: "true" 
          node.data: "false"
          node.ingest: "false"
          search.remote.connect: "false"
          cluster.name: "escluster"
          network.host: "_eth0_"
          network.publish_host: "128.122.72.33"
          discovery.zen.ping.unicast.hosts: "128.122.72.33,128.122.72.31,128.122.72.32"
          discovery.zen.minimum_master_nodes: "1"
          cluster.initial_master_nodes: "es01"


- hosts: docker_swarm_worker
  tasks:
    - name: Elasticsearch | Create container
      docker_container:
        name: "es_{{ inventory_hostname }}"
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        volumes:
          - /var/sonyc:/var/sonyc
        ports:
          - 9200:9200
          - 9300:9300    
        env:
          node.name: "es_{{ inventory_hostname }}"
          node.master: "false" 
          node.data: "true"
          node.ingest: "false"
          search.remote.connect: "false"
          cluster.name: "escluster"
          network.host: "_eth0_"
          network.publish_host: "{{ ansible_host }}"
          discovery.zen.ping.unicast.hosts: "128.122.72.33,128.122.72.31,128.122.72.32"
          discovery.zen.minimum_master_nodes: "1"
          cluster.initial_master_nodes: "es01"
