VAGRANTFILE_API_VERSION = "2"

servers=[
  {
    :hostname => "master",
    :ip => "192.168.200.10",
    :box => "ubuntu/xenial64",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "worker1",
    :ip => "192.168.200.11",
    :box => "ubuntu/xenial64",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "worker2",
    :ip => "192.168.200.12",
    :box => "ubuntu/xenial64",
    :ram => 1024,
    :cpu => 2
  }
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  servers.each_with_index do |machine, index|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.ssh.insert_key = false
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]          
      end
    end
    #if index == servers.size-1
    #  config.vm.provision :ansible do |ansible|
    #    ansible.limit = "all"
    #    ansible.playbook = "playbook.yml"
    #    ansible.inventory_path = "inventory"
    #  end
    #end
  end
end
